{
	"test":
		{
			"route":"test",
			"port":5550,
			"proxy_file":"proxy.txt",
			"urls":
				[
					"http://weibo.com/"
				]
		},
	"taobao":
		{
			"comment1":
			{
				"route":"taobao.comment",
				"port":5555,
				"proxy_file":"proxy.txt",
				"urls":
					[
						"http://rate.taobao.com/user-rate-fdba97de18d2adebd0c5b00d8ac66548.htm"
					],				
				"user_id":56651352,
				"page":1
			},
			"comment2":
			{
				"route":"taobao.comment",
				"port":5556,
				"proxy_file":"proxy.txt",
				"urls":
					[
						"http://rate.taobao.com/user-rate-c2cae03904ecaaae52707ce786d00f6f.htm"
					],				
				"user_id":103195305,
				"page":1
			},
			"jie":
			{
				"route":"taobao.jie",
				"port":5565,
				"proxy_file":"proxy.txt",
				"urls":
					[
						"http://jie.taobao.com/comment.htm?shopId=59199699"
					]
			}
		},
	"51job":
		{
		}
}
